name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t associative-property .

      - name: Save artifact
        run: docker run --rm associative-property > answer_associativity.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: answer_associativity
          path: answer_associativity.txt

  commit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "ci-bot@users.noreply.github.com"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: answer_associativity

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add answer_associativity.txt
          git commit -m "Add computed result"
          git push origin HEAD:main
