name: CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t associative-property .

      - name: Save artifact
        run: docker run --rm associative-property > answer_associativity.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: answer_associativity
          path: answer_associativity.txt

  analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Random runner
        run: |
          pip install -U numpy
          python runner.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data_csv
          path: data.csv

  commit:
    runs-on: ubuntu-latest
    needs: [build, analysis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Commit and push changes
        run: |
          git add answer_associativity.txt data.csv
          git commit -m "Add computed result"
          git push
